### ISSUE TITLE
RoR group project Recipe app: set up your Kanban board

### ISSUE THREAD

**Issue by carlosmuerto** [carlosmuerto/rails_recipe_app#2]
# Set up your Kanban board
- [Kanban board](https://github.com/users/carlosmuerto/projects/8/)
- [Repository](https://github.com/carlosmuerto/rails_recipe_app)
- [Assing Chart](https://github.com/users/carlosmuerto/projects/8/insights/1)
## Students
- @carlosmuerto 
- @Aseadd 

## Project requirements

- Join a Zoom call with your team. Only one person needs to create the board on behalf of the entire team but everybody should help during the call.
- Create an [empty repository](https://github.com/carlosmuerto/rails_recipe_app) for your group project.
- Open the GitHub project ([Kanban board](https://github.com/users/carlosmuerto/projects/8/)) in your team repo (set up the same columns as in previous group projects).
- Open [project requirements](https://github.com/microverseinc/curriculum-rails/blob/main/recipe-app/buisness_requirements.md) and read them carefully.
- Create tasks on your Kanban board based on the [project requirements](https://github.com/microverseinc/curriculum-rails/blob/main/recipe-app/buisness_requirements.md).
- Each task should be a separate card that:
    - Has a descriptive title.
    - Has the number of points in the `[Xpt]` prefix. That number should indicate the number of `points` that show how complex the task is. **1 point = 1 hour of estimated work**. You shouldn't change the points after dividing up cards, even if the actual work takes longer.
    - Has a description of the task.
- Each of the team members should assign themselves to the cards (and time estimate distributions should be fair - no single person should be doing all of the most time-consuming tasks). Decide who will be the assignee for the cards marked as group tasks. All cards on your Kanban board should have assignees. 
**NOTE you should distribite tasks in a way that gives each team member a chance to work with different parts of RoR. The number of assigned points should be equal (+/- 5 points) for each member.**
- [Open a new issue in your repository](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-an-issue).
    - In its description, paste a link to your [GitHub project](https://github.com/users/carlosmuerto/projects/8/).
    - Add a note telling the reviewer how many people there are in your team.
- Use the issue link to ask for a review. A code reviewer will leave you feedback in the issue's comment.
    - As it is your first time using a GitHub project and Kanban board, we need to double-check your setup to avoid problems while working on your project.

#### FULL [README](https://github.com/microverseinc/curriculum-rails/blob/main/recipe-app/setup_kanban_board.md)

**Comment by rloterh** [comment]
## Status: Approved :heavy_check_mark:

Hi Team,  

Your task is complete! 🍾🍾 Congratulations!  🎉💯🌟 

## Highlights 👍
- Board has required number of tasks
- Fair distribution of tasks

Keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
